apiVersion: v1
kind: Service
metadata:
  name: secureapp-service
spec:
  type: NodePort
  selector:
    app: secureapp
  ports:
    - protocol: TCP
      port: 8080           # internal container port
      targetPort: 8080     # containerPort
      nodePort: 30081      # external port → access via localhost:30081